/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pacote;

import java.io.IOException;
import java.io.RandomAccessFile;
import javax.swing.JOptionPane;

/**
 *
 * @author Vilson
 */
public class Tela extends javax.swing.JFrame {
    
    int increment = 1;
    
    String nome = "";
    String nontato = "";
    String rua = "";
    String numero = "";
    String bairro = "";
    String referencia = "";
    String sabor = "0";
    String precoPastel = "0";
    String qtdCoquinha = "0";
    String qtdCaldo = "0";
    String qtdSuco = "0";
    String qtdAgua = "0";

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSabores = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        venda = new javax.swing.JTabbedPane();
        jpanelBackground = new javax.swing.JPanel();
        jlabelSabores = new javax.swing.JLabel();
        jlabelBebidas = new javax.swing.JLabel();
        carne = new javax.swing.JRadioButton();
        queijo = new javax.swing.JRadioButton();
        calabresa = new javax.swing.JRadioButton();
        pizza = new javax.swing.JRadioButton();
        frango = new javax.swing.JRadioButton();
        doce = new javax.swing.JRadioButton();
        jpPrecoCarne = new javax.swing.JLabel();
        jpPrecoCalabresa = new javax.swing.JLabel();
        jpPrecoFrango = new javax.swing.JLabel();
        jpPrecoQueijo = new javax.swing.JLabel();
        jpPrecoPizza = new javax.swing.JLabel();
        jpPrecoDoce = new javax.swing.JLabel();
        jpDiv0 = new javax.swing.JPanel();
        jpDiv1 = new javax.swing.JPanel();
        jpDiv2 = new javax.swing.JPanel();
        jpDiv3 = new javax.swing.JPanel();
        jpDiv4 = new javax.swing.JPanel();
        jpDiv5 = new javax.swing.JPanel();
        jpDiv6 = new javax.swing.JPanel();
        jpDiv7 = new javax.swing.JPanel();
        coquinha = new javax.swing.JCheckBox();
        caldo = new javax.swing.JCheckBox();
        suco = new javax.swing.JCheckBox();
        agua = new javax.swing.JCheckBox();
        jpPrecoCoquinha = new javax.swing.JLabel();
        jpPrecoCaldo = new javax.swing.JLabel();
        jpPrecoSuco = new javax.swing.JLabel();
        jpPrecoAgua = new javax.swing.JLabel();
        jpDiv8 = new javax.swing.JPanel();
        jpDiv9 = new javax.swing.JPanel();
        jpDiv10 = new javax.swing.JPanel();
        jpDiv11 = new javax.swing.JPanel();
        jbTotalizar = new javax.swing.JButton();
        resultado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbZerar = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        cliente = new javax.swing.JPanel();
        labelCliente = new javax.swing.JLabel();
        jpDiv12 = new javax.swing.JPanel();
        jpDiv13 = new javax.swing.JPanel();
        jpDiv14 = new javax.swing.JPanel();
        jpDiv18 = new javax.swing.JPanel();
        jpDiv20 = new javax.swing.JPanel();
        jpDiv21 = new javax.swing.JPanel();
        jpDiv22 = new javax.swing.JPanel();
        jpDiv23 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jbZerar1 = new javax.swing.JButton();
        jbSair1 = new javax.swing.JButton();
        labelEntrega = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        labelRua = new javax.swing.JLabel();
        labelContato = new javax.swing.JLabel();
        labelNumero = new javax.swing.JLabel();
        labelBairro = new javax.swing.JLabel();
        labelRef = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        campoContato = new javax.swing.JTextField();
        campoRua = new javax.swing.JTextField();
        campoNumero = new javax.swing.JTextField();
        campoBairro = new javax.swing.JTextField();
        campoRef = new javax.swing.JTextField();
        jbRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jpanelBackground.setBackground(new java.awt.Color(255, 190, 0));
        jpanelBackground.setPreferredSize(new java.awt.Dimension(472, 710));

        jlabelSabores.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jlabelSabores.setForeground(new java.awt.Color(116, 0, 13));
        jlabelSabores.setText("SABORES:");

        jlabelBebidas.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jlabelBebidas.setForeground(new java.awt.Color(116, 0, 13));
        jlabelBebidas.setText("BEBIDAS:");

        carne.setBackground(new java.awt.Color(255, 190, 0));
        bgSabores.add(carne);
        carne.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        carne.setText("CARNE");
        carne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carneActionPerformed(evt);
            }
        });

        queijo.setBackground(new java.awt.Color(255, 190, 0));
        bgSabores.add(queijo);
        queijo.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        queijo.setText("QUEIJO");
        queijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queijoActionPerformed(evt);
            }
        });

        calabresa.setBackground(new java.awt.Color(255, 190, 0));
        bgSabores.add(calabresa);
        calabresa.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        calabresa.setText("CALABRESA");
        calabresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calabresaActionPerformed(evt);
            }
        });

        pizza.setBackground(new java.awt.Color(255, 190, 0));
        bgSabores.add(pizza);
        pizza.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        pizza.setText("PIZZA");
        pizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pizzaActionPerformed(evt);
            }
        });

        frango.setBackground(new java.awt.Color(255, 190, 0));
        bgSabores.add(frango);
        frango.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        frango.setText("FRANGO");
        frango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frangoActionPerformed(evt);
            }
        });

        doce.setBackground(new java.awt.Color(255, 190, 0));
        bgSabores.add(doce);
        doce.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        doce.setText("DOCE DE LEITE");
        doce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doceActionPerformed(evt);
            }
        });

        jpPrecoCarne.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jpPrecoCarne.setForeground(new java.awt.Color(204, 0, 0));
        jpPrecoCarne.setText("R$ 9");

        jpPrecoCalabresa.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jpPrecoCalabresa.setForeground(new java.awt.Color(204, 0, 0));
        jpPrecoCalabresa.setText("R$ 7");

        jpPrecoFrango.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jpPrecoFrango.setForeground(new java.awt.Color(204, 0, 0));
        jpPrecoFrango.setText("R$ 8");

        jpPrecoQueijo.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jpPrecoQueijo.setForeground(new java.awt.Color(204, 0, 0));
        jpPrecoQueijo.setText("R$ 9");

        jpPrecoPizza.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jpPrecoPizza.setForeground(new java.awt.Color(204, 0, 0));
        jpPrecoPizza.setText("R$ 9");

        jpPrecoDoce.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jpPrecoDoce.setForeground(new java.awt.Color(204, 0, 0));
        jpPrecoDoce.setText("R$ 6");

        jpDiv0.setBackground(new java.awt.Color(249, 97, 22));

        javax.swing.GroupLayout jpDiv0Layout = new javax.swing.GroupLayout(jpDiv0);
        jpDiv0.setLayout(jpDiv0Layout);
        jpDiv0Layout.setHorizontalGroup(
            jpDiv0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 129, Short.MAX_VALUE)
        );
        jpDiv0Layout.setVerticalGroup(
            jpDiv0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jpDiv1.setBackground(new java.awt.Color(249, 97, 22));

        javax.swing.GroupLayout jpDiv1Layout = new javax.swing.GroupLayout(jpDiv1);
        jpDiv1.setLayout(jpDiv1Layout);
        jpDiv1Layout.setHorizontalGroup(
            jpDiv1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );
        jpDiv1Layout.setVerticalGroup(
            jpDiv1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        jpDiv2.setBackground(new java.awt.Color(249, 97, 22));

        javax.swing.GroupLayout jpDiv2Layout = new javax.swing.GroupLayout(jpDiv2);
        jpDiv2.setLayout(jpDiv2Layout);
        jpDiv2Layout.setHorizontalGroup(
            jpDiv2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );
        jpDiv2Layout.setVerticalGroup(
            jpDiv2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        jpDiv3.setBackground(new java.awt.Color(249, 97, 22));

        javax.swing.GroupLayout jpDiv3Layout = new javax.swing.GroupLayout(jpDiv3);
        jpDiv3.setLayout(jpDiv3Layout);
        jpDiv3Layout.setHorizontalGroup(
            jpDiv3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );
        jpDiv3Layout.setVerticalGroup(
            jpDiv3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        jpDiv4.setBackground(new java.awt.Color(249, 97, 22));

        javax.swing.GroupLayout jpDiv4Layout = new javax.swing.GroupLayout(jpDiv4);
        jpDiv4.setLayout(jpDiv4Layout);
        jpDiv4Layout.setHorizontalGroup(
            jpDiv4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );
        jpDiv4Layout.setVerticalGroup(
            jpDiv4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        jpDiv5.setBackground(new java.awt.Color(249, 97, 22));

        javax.swing.GroupLayout jpDiv5Layout = new javax.swing.GroupLayout(jpDiv5);
        jpDiv5.setLayout(jpDiv5Layout);
        jpDiv5Layout.setHorizontalGroup(
            jpDiv5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );
        jpDiv5Layout.setVerticalGroup(
            jpDiv5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        jpDiv6.setBackground(new java.awt.Color(249, 97, 22));

        javax.swing.GroupLayout jpDiv6Layout = new javax.swing.GroupLayout(jpDiv6);
        jpDiv6.setLayout(jpDiv6Layout);
        jpDiv6Layout.setHorizontalGroup(
            jpDiv6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 129, Short.MAX_VALUE)
        );
        jpDiv6Layout.setVerticalGroup(
            jpDiv6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jpDiv7.setBackground(new java.awt.Color(249, 97, 22));

        javax.swing.GroupLayout jpDiv7Layout = new javax.swing.GroupLayout(jpDiv7);
        jpDiv7.setLayout(jpDiv7Layout);
        jpDiv7Layout.setHorizontalGroup(
            jpDiv7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );
        jpDiv7Layout.setVerticalGroup(
            jpDiv7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        coquinha.setBackground(new java.awt.Color(255, 190, 0));
        coquinha.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        coquinha.setText("COQUINHA");
        coquinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coquinhaActionPerformed(evt);
            }
        });

        caldo.setBackground(new java.awt.Color(255, 190, 0));
        caldo.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        caldo.setText("CALDO DE CANA");
        caldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caldoActionPerformed(evt);
            }
        });

        suco.setBackground(new java.awt.Color(255, 190, 0));
        suco.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        suco.setText("SUCO DE LARANJA");
        suco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sucoActionPerformed(evt);
            }
        });

        agua.setBackground(new java.awt.Color(255, 190, 0));
        agua.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        agua.setText("AGUA S/GAS");
        agua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aguaActionPerformed(evt);
            }
        });

        jpPrecoCoquinha.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jpPrecoCoquinha.setForeground(new java.awt.Color(204, 0, 0));
        jpPrecoCoquinha.setText("R$ 5");

        jpPrecoCaldo.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jpPrecoCaldo.setForeground(new java.awt.Color(204, 0, 0));
        jpPrecoCaldo.setText("R$ 4");

        jpPrecoSuco.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jpPrecoSuco.setForeground(new java.awt.Color(204, 0, 0));
        jpPrecoSuco.setText("R$ 7");

        jpPrecoAgua.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jpPrecoAgua.setForeground(new java.awt.Color(204, 0, 0));
        jpPrecoAgua.setText("R$ 3");

        jpDiv8.setBackground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout jpDiv8Layout = new javax.swing.GroupLayout(jpDiv8);
        jpDiv8.setLayout(jpDiv8Layout);
        jpDiv8Layout.setHorizontalGroup(
            jpDiv8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );
        jpDiv8Layout.setVerticalGroup(
            jpDiv8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        jpDiv9.setBackground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout jpDiv9Layout = new javax.swing.GroupLayout(jpDiv9);
        jpDiv9.setLayout(jpDiv9Layout);
        jpDiv9Layout.setHorizontalGroup(
            jpDiv9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );
        jpDiv9Layout.setVerticalGroup(
            jpDiv9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        jpDiv10.setBackground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout jpDiv10Layout = new javax.swing.GroupLayout(jpDiv10);
        jpDiv10.setLayout(jpDiv10Layout);
        jpDiv10Layout.setHorizontalGroup(
            jpDiv10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );
        jpDiv10Layout.setVerticalGroup(
            jpDiv10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        jpDiv11.setBackground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout jpDiv11Layout = new javax.swing.GroupLayout(jpDiv11);
        jpDiv11.setLayout(jpDiv11Layout);
        jpDiv11Layout.setHorizontalGroup(
            jpDiv11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );
        jpDiv11Layout.setVerticalGroup(
            jpDiv11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        jbTotalizar.setBackground(new java.awt.Color(122, 181, 3));
        jbTotalizar.setText("TOTALIZAR");
        jbTotalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTotalizarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vilson\\Documents\\NetBeansProjects\\PontoCerto\\logo.jpg")); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vilson\\Documents\\NetBeansProjects\\PontoCerto\\pastel.jpg")); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vilson\\Documents\\NetBeansProjects\\PontoCerto\\pastel-frito-na-hora.jpg")); // NOI18N
        jLabel3.setText("jLabel3");

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));

        jbZerar.setBackground(new java.awt.Color(122, 181, 3));
        jbZerar.setText("ZERAR");
        jbZerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbZerarActionPerformed(evt);
            }
        });

        jbSair.setBackground(new java.awt.Color(122, 181, 3));
        jbSair.setText("SAIR");
        jbSair.setMaximumSize(new java.awt.Dimension(65, 23));
        jbSair.setMinimumSize(new java.awt.Dimension(65, 23));
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jbZerar)
                .addGap(18, 18, 18)
                .addComponent(jbSair, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbZerar)
                    .addComponent(jbSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpanelBackgroundLayout = new javax.swing.GroupLayout(jpanelBackground);
        jpanelBackground.setLayout(jpanelBackgroundLayout);
        jpanelBackgroundLayout.setHorizontalGroup(
            jpanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpanelBackgroundLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jbTotalizar)
                .addGap(18, 18, 18)
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jpanelBackgroundLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jpanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelBackgroundLayout.createSequentialGroup()
                        .addGroup(jpanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanelBackgroundLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100))
                            .addComponent(jlabelSabores)
                            .addComponent(jpDiv0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelBackgroundLayout.createSequentialGroup()
                        .addGroup(jpanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jpPrecoSuco)
                            .addGroup(jpanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jpDiv10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jpDiv9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlabelBebidas)
                                .addComponent(jpDiv6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jpanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jpanelBackgroundLayout.createSequentialGroup()
                                        .addGroup(jpanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(suco, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(caldo, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jpPrecoCaldo))
                                    .addComponent(jpDiv8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpanelBackgroundLayout.createSequentialGroup()
                                        .addComponent(coquinha)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jpPrecoCoquinha))
                                    .addGroup(jpanelBackgroundLayout.createSequentialGroup()
                                        .addComponent(carne)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jpPrecoCarne))
                                    .addGroup(jpanelBackgroundLayout.createSequentialGroup()
                                        .addComponent(queijo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jpPrecoQueijo))
                                    .addGroup(jpanelBackgroundLayout.createSequentialGroup()
                                        .addComponent(agua)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jpPrecoAgua))
                                    .addComponent(jpDiv11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jpDiv1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jpDiv2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jpDiv4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpDiv7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelBackgroundLayout.createSequentialGroup()
                                    .addComponent(frango)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jpPrecoFrango))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelBackgroundLayout.createSequentialGroup()
                                    .addComponent(pizza)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jpPrecoPizza))
                                .addComponent(jpDiv3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelBackgroundLayout.createSequentialGroup()
                                    .addComponent(doce)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jpPrecoDoce))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelBackgroundLayout.createSequentialGroup()
                                    .addComponent(calabresa)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jpPrecoCalabresa))
                                .addComponent(jpDiv5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jpanelBackgroundLayout.setVerticalGroup(
            jpanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelBackgroundLayout.createSequentialGroup()
                .addGroup(jpanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jpanelBackgroundLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpanelBackgroundLayout.createSequentialGroup()
                        .addGroup(jpanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(jpanelBackgroundLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlabelSabores)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jpDiv0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jpanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carne)
                    .addComponent(jpPrecoCarne))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpDiv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(queijo)
                    .addComponent(jpPrecoQueijo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpDiv2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pizza)
                    .addComponent(jpPrecoPizza))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpDiv3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frango)
                    .addComponent(jpPrecoFrango))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpDiv4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calabresa)
                    .addComponent(jpPrecoCalabresa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpDiv5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doce)
                    .addComponent(jpPrecoDoce))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpDiv7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlabelBebidas)
                .addGap(4, 4, 4)
                .addComponent(jpDiv6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jpanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coquinha)
                    .addComponent(jpPrecoCoquinha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpDiv8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpPrecoCaldo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(caldo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpDiv9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suco)
                    .addComponent(jpPrecoSuco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpDiv10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agua)
                    .addComponent(jpPrecoAgua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpDiv11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbTotalizar))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        venda.addTab("VENDA", jpanelBackground);

        cliente.setBackground(new java.awt.Color(255, 190, 0));
        cliente.setPreferredSize(new java.awt.Dimension(472, 710));

        labelCliente.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        labelCliente.setForeground(new java.awt.Color(116, 0, 13));
        labelCliente.setText("CLIENTE:");

        jpDiv12.setBackground(new java.awt.Color(249, 97, 22));

        javax.swing.GroupLayout jpDiv12Layout = new javax.swing.GroupLayout(jpDiv12);
        jpDiv12.setLayout(jpDiv12Layout);
        jpDiv12Layout.setHorizontalGroup(
            jpDiv12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 129, Short.MAX_VALUE)
        );
        jpDiv12Layout.setVerticalGroup(
            jpDiv12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jpDiv13.setBackground(new java.awt.Color(249, 97, 22));

        javax.swing.GroupLayout jpDiv13Layout = new javax.swing.GroupLayout(jpDiv13);
        jpDiv13.setLayout(jpDiv13Layout);
        jpDiv13Layout.setHorizontalGroup(
            jpDiv13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );
        jpDiv13Layout.setVerticalGroup(
            jpDiv13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        jpDiv14.setBackground(new java.awt.Color(249, 97, 22));

        javax.swing.GroupLayout jpDiv14Layout = new javax.swing.GroupLayout(jpDiv14);
        jpDiv14.setLayout(jpDiv14Layout);
        jpDiv14Layout.setHorizontalGroup(
            jpDiv14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );
        jpDiv14Layout.setVerticalGroup(
            jpDiv14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        jpDiv18.setBackground(new java.awt.Color(249, 97, 22));

        javax.swing.GroupLayout jpDiv18Layout = new javax.swing.GroupLayout(jpDiv18);
        jpDiv18.setLayout(jpDiv18Layout);
        jpDiv18Layout.setHorizontalGroup(
            jpDiv18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 129, Short.MAX_VALUE)
        );
        jpDiv18Layout.setVerticalGroup(
            jpDiv18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jpDiv20.setBackground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout jpDiv20Layout = new javax.swing.GroupLayout(jpDiv20);
        jpDiv20.setLayout(jpDiv20Layout);
        jpDiv20Layout.setHorizontalGroup(
            jpDiv20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );
        jpDiv20Layout.setVerticalGroup(
            jpDiv20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        jpDiv21.setBackground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout jpDiv21Layout = new javax.swing.GroupLayout(jpDiv21);
        jpDiv21.setLayout(jpDiv21Layout);
        jpDiv21Layout.setHorizontalGroup(
            jpDiv21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );
        jpDiv21Layout.setVerticalGroup(
            jpDiv21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        jpDiv22.setBackground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout jpDiv22Layout = new javax.swing.GroupLayout(jpDiv22);
        jpDiv22.setLayout(jpDiv22Layout);
        jpDiv22Layout.setHorizontalGroup(
            jpDiv22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );
        jpDiv22Layout.setVerticalGroup(
            jpDiv22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        jpDiv23.setBackground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout jpDiv23Layout = new javax.swing.GroupLayout(jpDiv23);
        jpDiv23.setLayout(jpDiv23Layout);
        jpDiv23Layout.setHorizontalGroup(
            jpDiv23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );
        jpDiv23Layout.setVerticalGroup(
            jpDiv23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vilson\\Documents\\NetBeansProjects\\PontoCerto\\logo.jpg")); // NOI18N
        jLabel4.setText("jLabel1");

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vilson\\Documents\\NetBeansProjects\\PontoCerto\\pastel.jpg")); // NOI18N
        jLabel5.setText("jLabel2");

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vilson\\Documents\\NetBeansProjects\\PontoCerto\\pastel-frito-na-hora.jpg")); // NOI18N
        jLabel6.setText("jLabel3");

        jPanel3.setBackground(new java.awt.Color(255, 102, 0));

        jbZerar1.setBackground(new java.awt.Color(122, 181, 3));
        jbZerar1.setText("ZERAR");
        jbZerar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbZerar1ActionPerformed(evt);
            }
        });

        jbSair1.setBackground(new java.awt.Color(122, 181, 3));
        jbSair1.setText("SAIR");
        jbSair1.setMaximumSize(new java.awt.Dimension(65, 23));
        jbSair1.setMinimumSize(new java.awt.Dimension(65, 23));
        jbSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSair1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jbZerar1)
                .addGap(18, 18, 18)
                .addComponent(jbSair1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbZerar1)
                    .addComponent(jbSair1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 60, Short.MAX_VALUE))
        );

        labelEntrega.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        labelEntrega.setForeground(new java.awt.Color(116, 0, 13));
        labelEntrega.setText("ENTREGA:");

        labelNome.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        labelNome.setText("NOME:");

        labelRua.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        labelRua.setText("RUA:");

        labelContato.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        labelContato.setText("CONTATO:");

        labelNumero.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        labelNumero.setText("NÚMERO:");

        labelBairro.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        labelBairro.setText("BAIRRO:");

        labelRef.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        labelRef.setText("REF:");

        jbRegistrar.setBackground(new java.awt.Color(122, 181, 3));
        jbRegistrar.setText("REGISTRAR PEDIDO");
        jbRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbRegistrar.setMaximumSize(new java.awt.Dimension(65, 23));
        jbRegistrar.setMinimumSize(new java.awt.Dimension(65, 23));
        jbRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout clienteLayout = new javax.swing.GroupLayout(cliente);
        cliente.setLayout(clienteLayout);
        clienteLayout.setHorizontalGroup(
            clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(clienteLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clienteLayout.createSequentialGroup()
                        .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(clienteLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100))
                            .addComponent(labelCliente)
                            .addComponent(jpDiv12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(clienteLayout.createSequentialGroup()
                        .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(clienteLayout.createSequentialGroup()
                                .addComponent(labelNumero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelEntrega)
                            .addComponent(jpDiv22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpDiv18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clienteLayout.createSequentialGroup()
                                .addComponent(labelBairro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jpDiv21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clienteLayout.createSequentialGroup()
                                .addComponent(labelRua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campoRua, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(clienteLayout.createSequentialGroup()
                                .addComponent(labelRef)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campoRef, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jpDiv20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpDiv23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpDiv13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(clienteLayout.createSequentialGroup()
                                .addComponent(labelContato)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campoContato, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jpDiv14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clienteLayout.createSequentialGroup()
                                .addComponent(labelNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        clienteLayout.setVerticalGroup(
            clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clienteLayout.createSequentialGroup()
                .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(clienteLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(20, 20, 20))
                    .addGroup(clienteLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpDiv12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addGap(11, 11, 11)
                .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpDiv13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelContato)
                    .addComponent(campoContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpDiv14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169)
                .addComponent(labelEntrega)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpDiv18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRua))
                .addGap(7, 7, 7)
                .addComponent(jpDiv20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumero)
                    .addComponent(campoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jpDiv21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBairro)
                    .addComponent(campoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpDiv22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRef)
                    .addComponent(campoRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpDiv23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        venda.addTab("CLIENTE", cliente);

        jScrollPane1.setViewportView(venda);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pizzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pizzaActionPerformed

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jbSairActionPerformed

    private void jbTotalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTotalizarActionPerformed
        // TODO add your handling code here:
        double total = 0;
        
        if(carne.isSelected()){
            total += 9;
            sabor = "Carne";
            precoPastel = "R$9";
        } else if(queijo.isSelected()){
            total += 9;
            sabor = "Queijo";
            precoPastel = "R$9";
        } else if(frango.isSelected()){
            total += 8;
            sabor = "Frango";
            precoPastel = "R$8";
        } else if(calabresa.isSelected()){
            total += 7;
            sabor = "Calabresa";
            precoPastel = "R$7";
        } else if(pizza.isSelected()){
            total += 9;
            sabor = "Pizza";
            precoPastel = "R$9";
        } else if(doce.isSelected()){
            total += 6;
            sabor = "Doce";
            precoPastel = "R$6";
        }
        
        if(coquinha.isSelected()){
            total += 5;
            qtdCoquinha = "1 - R$5";
        }
        if(caldo.isSelected()){
            total += 4;
            qtdCaldo = "1 - R$4";
        }
        if(suco.isSelected()){
            total += 7;
            qtdSuco = "1 - R$7";
        }
        if(agua.isSelected()){
            total += 3;
            qtdAgua = "1 - R$3";
        }
        
        String resultadoFinal = "R$" + total;
        resultado.setText(resultadoFinal);
          
        
    }//GEN-LAST:event_jbTotalizarActionPerformed

    private void carneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carneActionPerformed

    private void queijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_queijoActionPerformed

    private void frangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frangoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frangoActionPerformed

    private void calabresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calabresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calabresaActionPerformed

    private void doceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doceActionPerformed

    private void coquinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coquinhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coquinhaActionPerformed

    private void caldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caldoActionPerformed

    private void sucoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sucoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sucoActionPerformed

    private void aguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aguaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aguaActionPerformed

    private void jbZerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbZerarActionPerformed
        // TODO add your handling code here:
        bgSabores.clearSelection();
        
        coquinha.setSelected(false);
        caldo.setSelected(false);
        suco.setSelected(false);
        agua.setSelected(false);
        
        resultado.setText("");
    }//GEN-LAST:event_jbZerarActionPerformed

    private void jbSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSair1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jbSair1ActionPerformed

    private void jbZerar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbZerar1ActionPerformed
        // TODO add your handling code here:
       campoNome.setText("");
       campoContato.setText("");
       campoRua.setText("");
       campoNumero.setText("");
       campoBairro.setText("");
       campoRef.setText("");
    }//GEN-LAST:event_jbZerar1ActionPerformed

    private void jbRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegistrarActionPerformed
        // TODO add your handling code here:
        if(campoNome.getText().equals("")){
            JOptionPane.showMessageDialog(cliente, "O seguinte campo precisa ser preenchido: [Nome]");
        } else if(campoContato.getText().equals("")){
            JOptionPane.showMessageDialog(cliente, "O seguinte campo precisa ser preenchido: [Contato]");
        } else if(campoRua.getText().equals("")){
            JOptionPane.showMessageDialog(cliente, "O seguinte campo precisa ser preenchido: [Rua]");
        } else if(campoNumero.getText().equals("")){
            JOptionPane.showMessageDialog(cliente, "O seguinte campo precisa ser preenchido: [Numero]");
        } else if(campoBairro.getText().equals("")){
            JOptionPane.showMessageDialog(cliente, "O seguinte campo precisa ser preenchido: [Bairro]");
        } else if(resultado.getText().equals("")){
            JOptionPane.showMessageDialog(venda, "Pedido não totalizado!");
        } else if(resultado.getText().equals("R$0.0")){
            JOptionPane.showMessageDialog(venda, "Pedido vazio!");
        } else {
            String entrega = "Dados da Entrega: \n\n" 
                + "Nome do cliente: " + campoNome.getText() 
                + "\nContato do cliente: " + campoContato.getText()
                + "\nRua: " + campoRua.getText()
                + "\nNúmero: " + campoNumero.getText()
                + "\nBairro: " + campoBairro.getText()
                + "\nReferência: " + campoRef.getText()
                + "\n\nDados do Pedido: \n\n"
                + "Pastel Sabor: " + sabor + " - Preço: " + precoPastel
                + "\nBebidas: " 
                + "\nCoquinha: " + qtdCoquinha
                + "\nCaldo de cana: " + qtdCaldo
                + "\nSuco de laranja: " + qtdSuco
                + "\nÁgua s/gas: " + qtdAgua
                + "\n\nValor total: " + resultado.getText();
        
            byte[] buff = entrega.getBytes();

            try {
                // "c:\\testejava\\teste.txt"
                RandomAccessFile raf = new RandomAccessFile("./pedido" + increment + ".txt", "rw");
                raf.write(buff);
                increment++;
                JOptionPane.showMessageDialog(cliente, "Pedido Registrado!");
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        
        

        
        
    }//GEN-LAST:event_jbRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox agua;
    private javax.swing.ButtonGroup bgSabores;
    private javax.swing.JRadioButton calabresa;
    private javax.swing.JCheckBox caldo;
    private javax.swing.JTextField campoBairro;
    private javax.swing.JTextField campoContato;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoNumero;
    private javax.swing.JTextField campoRef;
    private javax.swing.JTextField campoRua;
    private javax.swing.JRadioButton carne;
    private javax.swing.JPanel cliente;
    private javax.swing.JCheckBox coquinha;
    private javax.swing.JRadioButton doce;
    private javax.swing.JRadioButton frango;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbRegistrar;
    private javax.swing.JButton jbSair;
    private javax.swing.JButton jbSair1;
    private javax.swing.JButton jbTotalizar;
    private javax.swing.JButton jbZerar;
    private javax.swing.JButton jbZerar1;
    private javax.swing.JLabel jlabelBebidas;
    private javax.swing.JLabel jlabelSabores;
    private javax.swing.JPanel jpDiv0;
    private javax.swing.JPanel jpDiv1;
    private javax.swing.JPanel jpDiv10;
    private javax.swing.JPanel jpDiv11;
    private javax.swing.JPanel jpDiv12;
    private javax.swing.JPanel jpDiv13;
    private javax.swing.JPanel jpDiv14;
    private javax.swing.JPanel jpDiv18;
    private javax.swing.JPanel jpDiv2;
    private javax.swing.JPanel jpDiv20;
    private javax.swing.JPanel jpDiv21;
    private javax.swing.JPanel jpDiv22;
    private javax.swing.JPanel jpDiv23;
    private javax.swing.JPanel jpDiv3;
    private javax.swing.JPanel jpDiv4;
    private javax.swing.JPanel jpDiv5;
    private javax.swing.JPanel jpDiv6;
    private javax.swing.JPanel jpDiv7;
    private javax.swing.JPanel jpDiv8;
    private javax.swing.JPanel jpDiv9;
    private javax.swing.JLabel jpPrecoAgua;
    private javax.swing.JLabel jpPrecoCalabresa;
    private javax.swing.JLabel jpPrecoCaldo;
    private javax.swing.JLabel jpPrecoCarne;
    private javax.swing.JLabel jpPrecoCoquinha;
    private javax.swing.JLabel jpPrecoDoce;
    private javax.swing.JLabel jpPrecoFrango;
    private javax.swing.JLabel jpPrecoPizza;
    private javax.swing.JLabel jpPrecoQueijo;
    private javax.swing.JLabel jpPrecoSuco;
    private javax.swing.JPanel jpanelBackground;
    private javax.swing.JLabel labelBairro;
    private javax.swing.JLabel labelCliente;
    private javax.swing.JLabel labelContato;
    private javax.swing.JLabel labelEntrega;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNumero;
    private javax.swing.JLabel labelRef;
    private javax.swing.JLabel labelRua;
    private javax.swing.JRadioButton pizza;
    private javax.swing.JRadioButton queijo;
    private javax.swing.JTextField resultado;
    private javax.swing.JCheckBox suco;
    private javax.swing.JTabbedPane venda;
    // End of variables declaration//GEN-END:variables
}
